# Generated by Django 5.0.3 on 2024-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0003_rename_fole_personsroles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
