# Generated by Django 5.0.3 on 2024-04-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createTime',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
