# Generated by Django 5.0.3 on 2024-04-04 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0009_rename_createtime_review_create_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(blank=True, choices=[('like', 'Положительный'), ('dislike', 'Отрицательный'), ('neutral', 'Нейтральный')], default='neutral', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', 'Положительный'), ('dislike', 'Отрицательный')], default='like', max_length=30)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка рецензии',
                'verbose_name_plural': 'Оценки рецензии',
                'unique_together': {('review', 'user')},
            },
        ),
    ]
