# Generated by Django 4.2 on 2024-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0010_alter_review_type_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='type',
            field=models.CharField(blank=True, choices=[('neutral', 'Нейтральный'), ('like', 'Положительный'), ('dislike', 'Отрицательный')], max_length=30, null=True),
        ),
    ]
