# Generated by Django 4.2 on 2024-04-23 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0016_alter_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
