# Generated by Django 5.0.4 on 2024-04-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0018_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
