# Generated by Django 5.0.4 on 2024-05-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0019_person_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='budget',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='income',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
